[package]
name = "rust_prez"
version = "0.1.0"
authors = ["Luca Bolognese <lucabol@microsoft.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'  # Optimize for size.

[dependencies]
rand = "0.8.3"
